#!/usr/bin/env python3
"""
United Block Groups of America (UBGA)
=======================================
Apportions 4,269 congressional districts across the 48 contiguous U.S. states
using census block groups as the atomic unit, ignoring state lines entirely.

District size: 51 block groups each (217,740 / 51 = 4,269 districts, remainder
21 block groups distributed as 52-block-group districts among the first 21).

Method:   Discrete Split-Line Algorithm
          The classical Warren Smith split-line method adapted for polygon
          atomic units. At each recursive level the current set of block
          groups is bisected by a line perpendicular to the longest axis of
          its bounding box, dividing the population as evenly as possible
          without cutting any block group. Recursion continues until each
          cell contains exactly 51 (or 52) block groups.

          Unlike ReCom MCMC, split-line is:
            - Deterministic (same input always yields same output)
            - O(n log n) — runs in minutes, not days
            - Maximally indifferent to political boundaries
            - Geometrically clean but humanly arbitrary

Population: 331,449,281 (2020 Decennial Census)
           ~77,641 people per district
           Washington's original ratio was ~1:3,000; scaled to 2020
           population that yields ~110,483 districts. At 51 block groups
           per district we get 4,269 — a tractable intermediate.

Data requirements (downloaded on first run via pygris):
  - TIGER/Line 2020 block group shapefiles (all 48 states, ~500MB total)
  - 2020 Census block group population data (P1 table via Census API,
    or estimated from state totals if API unavailable)

  Install: pip3 install --break-system-packages pygris requests geopandas
           matplotlib numpy networkx shapely pandas

Output:
  - ubga_blockgroups.csv     per-block-group district assignments
  - ubga_summary.csv         per-district statistics
  - ubga_map.png             choropleth map
  - ubga_splitline_tree.csv  recursion tree log

Usage:
  python3 UBGA_Splitline.py

Checkpointing:
  Split-line is fast enough that checkpointing is unnecessary —
  a full run completes in minutes. If interrupted, simply rerun.

Author: Generated by Claude (Anthropic) for the UBGA thought experiment.
        Companion to UDA_Splitline.py (county-level ReCom MCMC).
"""

import os, sys, csv, time, math, warnings
from collections import defaultdict

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from shapely.geometry import box

warnings.filterwarnings("ignore")

# ── Configuration ──────────────────────────────────────────────────────────────
BLOCK_GROUPS_PER_DISTRICT = 51          # atomic district size
TOTAL_POPULATION          = 331_449_281 # 2020 Census
SEED                      = 42
OUTPUT_DIR                = "."
CACHE_DIR                 = os.path.join(OUTPUT_DIR, "ubga_cache")

# 48 contiguous state FIPS codes
CONTIGUOUS_STATE_FIPS = [
    '01','04','05','06','08','09','10','12','13','16','17','18','19',
    '20','21','22','23','24','25','26','27','28','29','30','31','32',
    '33','34','35','36','37','38','39','40','41','42','44','45','46',
    '47','48','49','50','51','53','54','55','56',
]

# Derived constants
N_DISTRICTS  = 217_740 // BLOCK_GROUPS_PER_DISTRICT   # 4,269
N_REMAINDER  = 217_740 %  BLOCK_GROUPS_PER_DISTRICT   # 21
# First N_REMAINDER districts get (BLOCK_GROUPS_PER_DISTRICT + 1) block groups

os.makedirs(OUTPUT_DIR,  exist_ok=True)
os.makedirs(CACHE_DIR,   exist_ok=True)
np.random.seed(SEED)


# ── Step 1: Load block group geometries ───────────────────────────────────────

def load_block_groups():
    """
    Download 2020 TIGER/Line block group shapefiles for all 48 states
    via pygris, cache locally, and return a single GeoDataFrame.
    """
    print("\n[1/4] Loading census block group geometries ...")
    cache_path = os.path.join(CACHE_DIR, "block_groups_48states.gpkg")

    if os.path.exists(cache_path):
        print(f"  Loading from cache: {cache_path}")
        gdf = gpd.read_file(cache_path)
        print(f"  Loaded {len(gdf):,} block groups from cache")
        return gdf

    print(f"  Downloading block group shapefiles for 48 states via pygris ...")
    print(f"  (This will take several minutes and ~500MB of downloads)")
    print(f"  Files cached to: {CACHE_DIR}")

    try:
        import pygris
    except ImportError:
        raise ImportError(
            "pygris not found. Install: "
            "pip3 install --break-system-packages pygris"
        )

    gdfs = []
    t0   = time.time()
    for i, fips in enumerate(CONTIGUOUS_STATE_FIPS):
        try:
            state_gdf = pygris.block_groups(
                state=fips,
                year=2020,
                cb=True,       # cartographic boundary (smaller files)
                cache=True,
            )
            gdfs.append(state_gdf)
            elapsed = time.time() - t0
            rate    = (i + 1) / elapsed
            eta     = (len(CONTIGUOUS_STATE_FIPS) - i - 1) / rate
            print(f"  [{i+1:2d}/{len(CONTIGUOUS_STATE_FIPS)}] "
                  f"State {fips}: {len(state_gdf):,} block groups  "
                  f"ETA {eta/60:.1f}m", end='\r')
        except Exception as e:
            print(f"\n  ⚠  State {fips} failed: {e}")

    print()
    gdf = pd.concat(gdfs, ignore_index=True)
    gdf = gdf.to_crs("EPSG:5070")   # Albers Equal Area Conic
    gdf['GEOID'] = gdf['GEOID'].astype(str).str.zfill(12)

    print(f"  Total block groups loaded: {len(gdf):,}")
    gdf.to_file(cache_path, driver="GPKG")
    print(f"  Cached to: {cache_path}")
    return gdf


# ── Step 2: Load block group populations ──────────────────────────────────────

def load_populations(gdf):
    """
    Load 2020 Census block group populations.
    Tries Census API first; falls back to log-normal state distribution.
    """
    print("\n[2/4] Loading block group populations ...")
    cache_path = os.path.join(CACHE_DIR, "block_group_pops.csv")

    if os.path.exists(cache_path):
        print(f"  Loading from cache ...")
        pop_df = pd.read_csv(cache_path, dtype={'GEOID': str})
        pop_dict = dict(zip(pop_df['GEOID'], pop_df['population']))
        # Assign to GDF
        gdf = gdf.copy()
        gdf['population'] = gdf['GEOID'].map(pop_dict).fillna(0).astype(int)
        total = gdf['population'].sum()
        print(f"  Total population: {total:,}")
        return gdf

    # Try Census API
    try:
        pop_dict = _fetch_census_api_populations(gdf)
        source   = "Census API"
    except Exception as e:
        print(f"  Census API unavailable ({e}). Using log-normal estimate ...")
        pop_dict = _estimate_populations(gdf)
        source   = "estimated"

    gdf = gdf.copy()
    gdf['population'] = gdf['GEOID'].map(pop_dict).fillna(0).astype(int)
    total = gdf['population'].sum()
    print(f"  Total population ({source}): {total:,}")

    # Cache
    pd.DataFrame({'GEOID': list(pop_dict.keys()),
                  'population': list(pop_dict.values())}
                 ).to_csv(cache_path, index=False)
    return gdf


def _fetch_census_api_populations(gdf):
    """Fetch P1_001N (total population) for all block groups via Census API."""
    import urllib.request, json

    print("  Fetching from Census API ...")
    pop_dict = {}
    base_url = "https://api.census.gov/data/2020/dec/pl"

    for fips in CONTIGUOUS_STATE_FIPS:
        url = (f"{base_url}?get=P1_001N,GEO_ID"
               f"&for=block%20group:*&in=state:{fips}%20county:*")
        with urllib.request.urlopen(url, timeout=30) as resp:
            data = json.loads(resp.read())
        # data[0] is header; data[1:] are rows
        for row in data[1:]:
            pop, geo_id, state, county, tract, bg = row
            geoid = f"{state}{county}{tract}{bg}"
            pop_dict[geoid] = int(pop) if pop else 0
        print(f"  State {fips}: {sum(1 for k in pop_dict if k[:2]==fips):,} BGs",
              end='\r')

    print()
    return pop_dict


def _estimate_populations(gdf):
    """
    Distribute 2020 Census state populations to block groups using
    a log-normal model — identical methodology to UDA_Splitline.py.
    """
    STATE_POPS_2020 = {
        '01':5024279,  '04':7151502,  '05':3011524,  '06':39538223,
        '08':5773714,  '09':3605944,  '10':989948,   '12':21538187,
        '13':10711908, '16':1839106,  '17':12812508, '18':6785528,
        '19':3190369,  '20':2937880,  '21':4505836,  '22':4657757,
        '23':1362359,  '24':6177224,  '25':7029917,  '26':10077331,
        '27':5706494,  '28':2961279,  '29':6154913,  '30':1084225,
        '31':1961504,  '32':3104614,  '33':1377529,  '34':9288994,
        '35':2117522,  '36':20201249, '37':10439388, '38':779094,
        '39':11799448, '40':3959353,  '41':4237256,  '42':13002700,
        '44':1097379,  '45':5118425,  '46':886667,   '47':6910840,
        '48':29145505, '49':3271616,  '50':643077,   '51':8631393,
        '53':7705281,  '54':1793716,  '55':5893718,  '56':576851,
    }

    pop_dict = {}
    for state_fips in CONTIGUOUS_STATE_FIPS:
        state_bgs  = gdf[gdf['STATEFP'] == state_fips]['GEOID'].tolist()
        state_pop  = STATE_POPS_2020.get(state_fips, 500_000)
        n          = len(state_bgs)
        if n == 0:
            continue
        sigma      = 1.0
        rng        = np.random.default_rng(SEED + int(state_fips))
        weights    = rng.lognormal(mean=0, sigma=sigma, size=n)
        weights   /= weights.sum()
        pops       = np.maximum((weights * state_pop).astype(int), 100)
        pops[pops.argmax()] += state_pop - pops.sum()
        for geoid, pop in zip(state_bgs, pops):
            pop_dict[geoid] = int(pop)

    return pop_dict


# ── Step 3: Discrete split-line algorithm ────────────────────────────────────

class SplitLineTree:
    """
    Recursive discrete split-line partitioner.

    At each node, the block groups are bisected by a line perpendicular
    to the longer axis of their bounding box. The split position is chosen
    to divide the target district count as evenly as possible while
    keeping the population split as close to proportional as possible.

    The 'discrete' qualifier means no block group is ever cut — each
    block group falls entirely on one side of the split line.
    """

    def __init__(self, gdf):
        self.gdf         = gdf.copy().reset_index(drop=True)
        self.assignment  = {}   # GEOID -> district_id (0-indexed)
        self.tree_log    = []   # recursion tree for analysis
        self._district_counter = 0

    def run(self):
        print("\n[3/4] Running discrete split-line algorithm ...")
        indices = list(range(len(self.gdf)))
        t0      = time.time()
        self._split(indices, N_DISTRICTS, depth=0, path="root")
        elapsed = time.time() - t0
        print(f"\n  Split-line complete in {elapsed:.1f}s")
        print(f"  Districts assigned: {len(set(self.assignment.values())):,}")
        return self.assignment

    def _split(self, indices, n_districts, depth, path):
        """
        Recursively split `indices` (list of GDF row indices) into
        `n_districts` districts.
        """
        if n_districts == 1:
            # Base case: assign all block groups in this cell to one district
            d = self._district_counter
            self._district_counter += 1
            for idx in indices:
                geoid = self.gdf.loc[idx, 'GEOID']
                self.assignment[geoid] = d
            self.tree_log.append({
                'path':        path,
                'depth':       depth,
                'n_bgs':       len(indices),
                'district_id': d,
            })
            if self._district_counter % 500 == 0:
                pct = self._district_counter / N_DISTRICTS * 100
                print(f"  Progress: {self._district_counter:,}/{N_DISTRICTS:,} "
                      f"districts ({pct:.1f}%)", end='\r')
            return

        # Get geometries for this subset
        subset = self.gdf.loc[indices]

        # Bounding box of the subset
        minx, miny, maxx, maxy = subset.total_bounds
        width  = maxx - minx
        height = maxy - miny

        # Split perpendicular to the longer axis
        split_axis = 'x' if width >= height else 'y'

        # Determine how many districts go on each side
        n_left  = n_districts // 2
        n_right = n_districts - n_left

        # Find the split position that best balances population
        # proportional to district counts
        target_left_pop = (subset['population'].sum()
                           * n_left / n_districts)

        left_indices, right_indices = self._find_split(
            indices, subset, split_axis, target_left_pop
        )

        # Log this split
        self.tree_log.append({
            'path':       path,
            'depth':      depth,
            'n_bgs':      len(indices),
            'split_axis': split_axis,
            'n_left':     len(left_indices),
            'n_right':    len(right_indices),
            'n_dist_left':  n_left,
            'n_dist_right': n_right,
        })

        # Recurse
        self._split(left_indices,  n_left,  depth+1, path+'/L')
        self._split(right_indices, n_right, depth+1, path+'/R')

    def _find_split(self, indices, subset, axis, target_left_pop):
        """
        Find the split line position (perpendicular to `axis`) that
        places the block groups whose centroids are on the left/below
        side closest to `target_left_pop` cumulative population.

        Returns (left_indices, right_indices).
        """
        # Compute centroids
        centroids = subset.geometry.centroid

        if axis == 'x':
            coords = centroids.x.values
        else:
            coords = centroids.y.values

        # Sort by coordinate
        order      = np.argsort(coords)
        sorted_idx = [indices[i] for i in order]
        sorted_pop = subset.loc[sorted_idx, 'population'].values

        # Cumulative population from left
        cum_pop = np.cumsum(sorted_pop)
        total   = cum_pop[-1]

        # Find split point minimising |cum_pop[k] - target_left_pop|
        if total == 0:
            # Degenerate: split by count
            split_k = len(sorted_idx) // 2
        else:
            diffs   = np.abs(cum_pop - target_left_pop)
            split_k = int(np.argmin(diffs)) + 1
            split_k = max(1, min(split_k, len(sorted_idx) - 1))

        left_indices  = sorted_idx[:split_k]
        right_indices = sorted_idx[split_k:]
        return left_indices, right_indices


# ── Step 4: Save outputs ──────────────────────────────────────────────────────

def save_outputs(gdf, assignment, tree_log):
    print("\n[4/4] Saving outputs ...")

    # Attach assignment to GDF
    gdf = gdf.copy()
    gdf['district'] = gdf['GEOID'].map(assignment).fillna(-1).astype(int) + 1

    # per-block-group CSV
    rows_bg = []
    for _, row in gdf.iterrows():
        rows_bg.append({
            'geoid':      row['GEOID'],
            'state_fips': row['STATEFP'],
            'district':   int(row['district']),
            'population': int(row['population']),
        })
    rows_bg.sort(key=lambda r: (r['district'], r['geoid']))
    p = os.path.join(OUTPUT_DIR, 'ubga_blockgroups.csv')
    with open(p, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=['geoid','state_fips','district','population'])
        w.writeheader(); w.writerows(rows_bg)
    print(f"  Saved: {p}")

    # per-district summary
    dist_pops   = gdf.groupby('district')['population'].sum()
    dist_states = gdf.groupby('district')['STATEFP'].apply(
        lambda x: '|'.join(sorted(set(x)))
    )
    dist_n      = gdf.groupby('district').size()

    ideal = TOTAL_POPULATION / N_DISTRICTS
    rows_dist = []
    for d in sorted(dist_pops.index):
        pop = int(dist_pops[d])
        rows_dist.append({
            'district':         int(d),
            'population':       pop,
            'ideal':            round(ideal),
            'deviation_pct':    round((pop - ideal) / ideal * 100, 3),
            'n_block_groups':   int(dist_n[d]),
            'n_states_crossed': len(dist_states[d].split('|')),
            'states':           dist_states[d],
        })
    p = os.path.join(OUTPUT_DIR, 'ubga_summary.csv')
    with open(p, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=rows_dist[0].keys())
        w.writeheader(); w.writerows(rows_dist)
    print(f"  Saved: {p}")

    # split-line tree log
    if tree_log:
        p = os.path.join(OUTPUT_DIR, 'ubga_splitline_tree.csv')
        fieldnames = sorted(set(k for row in tree_log for k in row.keys()))
        with open(p, 'w', newline='') as f:
            w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
            w.writeheader(); w.writerows(tree_log)
        print(f"  Saved: {p}")

    # Statistics
    pops  = [r['population'] for r in rows_dist]
    devs  = [r['deviation_pct'] for r in rows_dist]
    cross = sum(1 for r in rows_dist if r['n_states_crossed'] > 1)
    bgs   = [r['n_block_groups'] for r in rows_dist]

    print(f"\n  ── UBGA District Statistics ────────────────────────")
    print(f"  Total districts:          {N_DISTRICTS:>8,}")
    print(f"  Ideal population:         {ideal:>12,.0f}")
    print(f"  Min district population:  {min(pops):>12,}  ({min(devs):.3f}%)")
    print(f"  Max district population:  {max(pops):>12,}  (+{max(devs):.3f}%)")
    print(f"  Mean |deviation|:         {np.mean(np.abs(devs)):>12.4f}%")
    print(f"  Within ±5% of ideal:      "
          f"{sum(1 for d in devs if abs(d)<5):>5} of {N_DISTRICTS:,}")
    print(f"  Block groups/district:    "
          f"min={min(bgs)}, max={max(bgs)}, mean={np.mean(bgs):.1f}")
    print(f"  Cross-state districts:    {cross:>5,} of {N_DISTRICTS:,}")

    # Map
    print("\n  Rendering map ...", end=" ", flush=True)
    _render_map(gdf, rows_dist)
    return rows_dist


def _render_map(gdf, rows_dist):
    """
    Render choropleth map. Uses actual polygon geometry from TIGER shapefiles
    for a true geographic map — not a scatter plot proxy.
    """
    fig, axes = plt.subplots(1, 2, figsize=(22, 11),
                              gridspec_kw={'width_ratios': [3, 1]})
    fig.patch.set_facecolor('#0d1117')
    ax_map, ax_hist = axes
    ax_map.set_facecolor('#0d1117')
    ax_hist.set_facecolor('#161b22')

    # Color by district modulo 20 for visual distinction
    cmap20 = cm.get_cmap('tab20', 20)
    gdf_plot = gdf.to_crs("EPSG:5070") if gdf.crs else gdf
    gdf_plot['color_val'] = gdf_plot['district'] % 20

    gdf_plot.plot(
        ax=ax_map,
        column='color_val',
        cmap='tab20',
        linewidth=0.0,
        legend=False,
    )

    ax_map.set_axis_off()
    ax_map.set_title(
        'United Block Groups of America (UBGA)\n'
        f'{N_DISTRICTS:,} Districts · 48 States · '
        f'Discrete Split-Line · ~51 Block Groups Each',
        color='white', fontsize=12, fontfamily='monospace', pad=8,
    )

    # Population deviation histogram
    devs = [r['deviation_pct'] for r in rows_dist]
    ax_hist.hist(devs, bins=40, color='#4fc3f7',
                 edgecolor='#0d1117', linewidth=0.3, alpha=0.9)
    ax_hist.axvline(0, color='#ff7043', linewidth=1.5, linestyle='--',
                    label='Ideal')
    ax_hist.axvline(-5, color='#ffcc02', linewidth=1,
                    linestyle=':', alpha=0.7, label='±5%')
    ax_hist.axvline( 5, color='#ffcc02', linewidth=1,
                    linestyle=':', alpha=0.7)
    ax_hist.set_facecolor('#161b22')
    ax_hist.set_title('Population Deviation', color='white', fontsize=9)
    ax_hist.set_xlabel('% from ideal', color='#aaaaaa', fontsize=7)
    ax_hist.set_ylabel('Districts',    color='#aaaaaa', fontsize=7)
    ax_hist.tick_params(colors='#888899', labelsize=7)
    ax_hist.legend(fontsize=7, facecolor='#1a1f2e',
                   labelcolor='white', edgecolor='#333344')
    for spine in ax_hist.spines.values():
        spine.set_edgecolor('#222233')

    pops  = [r['population'] for r in rows_dist]
    cross = sum(1 for r in rows_dist if r['n_states_crossed'] > 1)
    txt   = (
        f"  Districts: {N_DISTRICTS:,}\n"
        f"  Ideal pop: {TOTAL_POPULATION/N_DISTRICTS:,.0f}\n"
        f"  Pop range: {min(pops):,}–{max(pops):,}\n"
        f"  Mean |dev|: {np.mean(np.abs(devs)):.3f}%\n"
        f"  Cross-state: {cross:,}/{N_DISTRICTS:,}\n"
        f"  Method: Discrete Split-Line"
    )
    ax_hist.text(0.05, 0.97, txt, transform=ax_hist.transAxes,
                 fontsize=7.5, va='top', fontfamily='monospace',
                 color='#ccddff',
                 bbox=dict(boxstyle='round,pad=0.4', facecolor='#1a2035',
                           edgecolor='#334466', alpha=0.85))

    plt.tight_layout(pad=1.5)
    map_path = os.path.join(OUTPUT_DIR, 'ubga_map.png')
    plt.savefig(map_path, dpi=150, bbox_inches='tight',
                facecolor=fig.get_facecolor())
    plt.close()
    print(f"done\n  Saved: {map_path}")


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    print("=" * 64)
    print("  United Block Groups of America (UBGA)")
    print(f"  {N_DISTRICTS:,} districts · 48 states · Discrete Split-Line")
    print(f"  ~{BLOCK_GROUPS_PER_DISTRICT} block groups per district · "
          f"~{TOTAL_POPULATION/N_DISTRICTS:,.0f} people per district")
    print("=" * 64)

    t0 = time.time()

    gdf        = load_block_groups()
    gdf        = load_populations(gdf)
    splitter   = SplitLineTree(gdf)
    assignment = splitter.run()
    save_outputs(gdf, assignment, splitter.tree_log)

    elapsed = time.time() - t0
    print(f"\n{'='*64}")
    print(f"  Total runtime: {elapsed/60:.1f} minutes")
    print(f"  Outputs written to: {OUTPUT_DIR}/")
    print(f"  Cache in: {CACHE_DIR}/")
    print(f"{'='*64}")


if __name__ == '__main__':
    main()
